
#include <iostream>
#include <cassert>
 
int main()
{
    assert(2+2==4); // true
    std::cout << "Execution continues past the first assert\n";
    assert(2+2==5); // false = > abort
    std::cout << "Execution continues past the second assert\n";
}

Possible output:

Execution continues past the first assert
test: test.cc:10: int main(): Assertion `2+2==5' failed.
Aborted

